---

- name: Install Wraith's dependencies
  apt: name={{ item }} state=present install_recommends=no update_cache=yes cache_valid_time=3600
  with_items:
    - libicu-dev
    - imagemagick
    - rake
    - ruby-dev
  sudo: yes

- name: Install Wraith gem
  sudo: yes
  command: gem install wraith -v '1.1.6' --no-rdoc --no-ri